<a href="https://colab.research.google.com/github/Varun-531/Data-Mining/blob/main/DWDM_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
from sklearn.datasets import load_iris
import pandas as pd

In [62]:
iris = load_iris()
data = pd.DataFrame(iris.data,columns = iris.feature_names)

In [63]:
data['target'] = iris.target

# **Cosine**

In [64]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity_result = cosine_similarity(data.iloc[[0]], data.iloc[[1]])
cosine_similarity_result

array([[0.99857916]])

# **Euclidean distance**

In [66]:
from sklearn.metrics.pairwise import euclidean_distances
euc_dis = euclidean_distances(data.iloc[[0]],data.iloc[[1]])
euc_dis

array([[0.53851648]])

# **Corr**

In [68]:
from scipy.stats import pearsonr
corr,_ = pearsonr(data['petal length (cm)'],data['sepal width (cm)'])
corr

-0.4284401043305397

# **Jaccard Similarity**

In [71]:
from sklearn.metrics import jaccard_score
import numpy as np

# Assuming 'data' is your DataFrame and 'target' is the column containing the target values
target_set_1 = set([data.iloc[0]['target']])
target_set_2 = set([data.iloc[1]['target']])

# Convert sets to lists and calculate Jaccard similarity
jac_sim = jaccard_score(list(target_set_1), list(target_set_2), average='micro')
jac_sim


1.0

# **Manhattan distance**

In [72]:
from sklearn.metrics.pairwise import manhattan_distances

# Assuming 'data' is your DataFrame
row_1 = data.iloc[[0], :-1]
row_2 = data.iloc[[1], :-1]

manhattan_dist = manhattan_distances(row_1, row_2)

# Ensure 'print' is not assigned to a variable
manhattan_dist


array([[0.7]])